version: '3.8'
services:

  db:
    image: postgres:15-alpine
    container_name: my-database
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: siscgmsis2025
      POSTGRES_DB: todo-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://root:siscgmsis2025@db:5432/todo-db"
      PORT: "3000"
      JWT_SECRET: "01951a38631b776ea5d19c06751ef9c4"

    labels:
      - traefik.enable=true

      - traefik.http.routers.project1-http.rule=Host(`todo-api.cgmcloud.com.br`)
      - traefik.http.routers.project1-http.entrypoints=http
      - traefik.http.routers.project1-http.middlewares=https-redirect

      - traefik.http.routers.project1-https.rule=Host(`todo-api.cgmcloud.com.br`)
      - traefik.http.routers.project1-https.entrypoints=https
      - traefik.http.routers.project1-https.tls=true
      - traefik.http.routers.project1-https.tls.certresolver=le
      - traefik.http.routers.project1-https.service=project1-service
      - traefik.http.services.project1-service.loadbalancer.server.port=3000
    networks:
      - traefik-public
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start

volumes:
  pg_data:

networks:
  traefik-public:
    external: true
