version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: siscgmsis2025
      POSTGRES_DB: todo-db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: express_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://root:siscgmsis2025@db:5432/todo-db"
      PORT: "3000"
      JWT_SECRET: "01951a38631b776ea5d19c06751ef9c4"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pg_data:
